// Package claudehook manages Claude Code's multi-event hook for Quil.
//
// Quil tracks Claude session-id rotation (/clear, compaction, /resume) and
// forwards Claude's lifecycle/notification hooks by registering a hook command
// via --settings (inline JSON) when it spawns a claude-code pane. The hook
// command invokes the quil daemon binary's `claude-hook` subcommand (see
// runhook.go + cmd/quild), which reads the hook JSON on stdin and writes the
// per-pane session id to $QUIL_HOME/sessions/<paneID>.id and/or appends a
// hookevents JSONL line to $QUIL_HOME/events/<paneID>.jsonl.
//
// Invoking the native binary instead of a per-event shell script eliminates
// the dominant hook latency (PowerShell 5.1 cold start was ~1-4 s) and the
// hand-rolled JSON escaping the shell producers required.
//
// This package never reads or writes ~/.claude/settings.json — the hook is
// per-invocation, lives entirely under QuilDir, and no user Claude config is
// mutated.
package claudehook

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// validatePaneID rejects pane ids that could let a caller escape the sessions
// directory. Defense-in-depth: today every caller routes through pane IDs
// generated by uuid + an isValidHexID guard, but the package keeps its own
// invariant so a future caller cannot accidentally read arbitrary files.
func validatePaneID(paneID string) error {
	if paneID == "" {
		return errors.New("claudehook: empty paneID")
	}
	if strings.ContainsAny(paneID, `/\`) || strings.Contains(paneID, "..") {
		return fmt.Errorf("claudehook: paneID %q contains path separators or parent traversal", paneID)
	}
	// Reject control characters (incl. newline) so a hostile pane id cannot
	// forge log lines when reflected into the hook log, nor smuggle a NUL that
	// truncates a path on some platforms. %q in the error escapes them safely.
	for _, r := range paneID {
		if r < 0x20 || r == 0x7f {
			return fmt.Errorf("claudehook: paneID %q contains a control character", paneID)
		}
	}
	return nil
}

// atomicWrite writes data to path via a temp file in the same directory and a
// rename. Removes the temp on any error so we never leak a half-written file.
func atomicWrite(path string, data []byte, perm os.FileMode) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, filepath.Base(path)+".tmp.*")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()
	// cleanup removes the half-written temp on any error. The Remove return
	// value is intentionally discarded: we are already returning an error to
	// the caller, and the dir is 0700 so a leaked temp is owner-only.
	cleanup := func() { _ = os.Remove(tmpPath) }
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		cleanup()
		return err
	}
	if err := tmp.Chmod(perm); err != nil {
		tmp.Close()
		cleanup()
		return err
	}
	if err := tmp.Close(); err != nil {
		cleanup()
		return err
	}
	if err := os.Rename(tmpPath, path); err != nil {
		cleanup()
		return err
	}
	return nil
}

// HookCommand returns the command Claude runs for each registered hook event.
// It invokes the running quil daemon binary's `claude-hook` subcommand, which
// reads the hook JSON on stdin and writes the session-id file / spool line
// natively. exePath must be the absolute path to the quild binary (the daemon
// passes os.Executable()); it is double-quoted so paths with spaces work under
// the shell Claude uses to run hook commands. The command is embedded in the
// --settings JSON via BuildSettingsJSON, which JSON-escapes it.
//
// exePath is the daemon's own binary location — OS-controlled, never user
// input — so a shell-metacharacter break-out is not a realistic concern; a `"`
// is illegal in a Windows path and effectively never appears on Unix.
func HookCommand(exePath string) string {
	return fmt.Sprintf(`"%s" claude-hook`, exePath)
}

// settingsSchema mirrors the subset of Claude Code's settings.json format
// we need to register hooks. Only the forwarded events are populated.
type settingsSchema struct {
	Hooks map[string][]hookMatcher `json:"hooks"`
}

type hookMatcher struct {
	// Matcher is an optional tool-name regex (Claude matches it against
	// tool_name for PreToolUse/PostToolUse). Empty = match all events.
	Matcher string      `json:"matcher,omitempty"`
	Hooks   []hookEntry `json:"hooks"`
}

type hookEntry struct {
	Type    string `json:"type"`
	Command string `json:"command"`
}

// forwardedHookEvents lists the Claude Code hook events Quil registers in
// the inline --settings JSON. The native claude-hook subcommand branches on
// hook_event_name from stdin so the same command handles every entry.
//
// SessionStart is the original — it writes the session id file used by the
// resume-args path. The rest are the v1 "default" tier from the hook events
// plan: notification + permission + lifecycle. These are registered match-all
// (no tool-name filter).
var forwardedHookEvents = []string{
	"SessionStart",
	"SessionEnd",
	"UserPromptSubmit",
	"Notification",
	"PermissionRequest",
	"Stop",
	// The turn ending Claude reports INSTEAD of Stop when the API call fails.
	// Without it a failed turn produced no turn-ending edge at all.
	"StopFailure",
	"PreCompact",
	"PostCompact",
	"SubagentStart",
	"SubagentStop",
	"TaskCreated",
	"TaskCompleted",
	// Match-all deliberately, unlike the PostToolUse entry below: this is the
	// start edge for a turn no user prompt began (a teammate reported back and
	// the agent resumed on its own), and a resumed turn's first action is
	// whatever tool the agent picks. Narrowing it by tool name would restore
	// the blind spot it closes. The per-tool-call volume is handled in the
	// producer instead — RunHook drops the line unless the pane has been quiet
	// (spoolIsFresh) — because a line dropped there cannot cost the signal.
	"PreToolUse",
}

// matchedHookEvents are registered with a tool-name matcher so Claude only
// invokes the hook for the listed tools — avoiding the per-tool-call overhead
// that kept the full PreToolUse/PostToolUse stream out of the default tier.
//
// PostToolUse for the interactive-prompt tools (AskUserQuestion, ExitPlanMode)
// is the "resume" edge: it fires the instant the user answers a prompt, which
// the TUI uses to re-arm the work spinner after a park (the park itself comes
// from the match-all PermissionRequest/Notification events above). Diagnostic
// hook logging confirmed PreToolUse fires *before* the prompt, so only
// PostToolUse can serve as the ANSWER edge — that is what this entry is about,
// and it is unaffected by PreToolUse also being registered match-all above for
// an unrelated purpose (proof that an autonomously resumed turn is running).
var matchedHookEvents = []struct{ Name, Matcher string }{
	{Name: "PostToolUse", Matcher: promptToolMatcher},
}

// promptToolMatcher is the tool-name regex for interactive-prompt tools whose
// completion re-arms the work spinner. Keep in sync with the PostToolUse case
// in runhook.go.
const promptToolMatcher = "AskUserQuestion|ExitPlanMode"

// BuildSettingsJSON returns the inline JSON string Quil passes to
// `claude --settings <json>`. Registers Quil's hook command under every
// entry in forwardedHookEvents — the native subcommand then branches on the
// hook_event_name field of the stdin JSON.
func BuildSettingsJSON(cmd string) (string, error) {
	s := settingsSchema{
		Hooks: make(map[string][]hookMatcher, len(forwardedHookEvents)+len(matchedHookEvents)),
	}
	for _, name := range forwardedHookEvents {
		s.Hooks[name] = []hookMatcher{{
			Hooks: []hookEntry{{Type: "command", Command: cmd}},
		}}
	}
	for _, me := range matchedHookEvents {
		s.Hooks[me.Name] = []hookMatcher{{
			Matcher: me.Matcher,
			Hooks:   []hookEntry{{Type: "command", Command: cmd}},
		}}
	}
	b, err := json.Marshal(s)
	if err != nil {
		return "", fmt.Errorf("marshal claude settings: %w", err)
	}
	return string(b), nil
}

// settingsFile returns the absolute path of the per-pane hook-settings JSON
// written under <quilDir>/sessions/. A file (rather than an inline --settings
// JSON string) is used because on Windows the claude/tclaude binary is an npm
// .cmd shim that cmd.exe re-parses: the quotes inside an inline JSON are
// stripped/reshaped by cmd.exe and the argument is split at the wrong
// boundaries, so the hook never registers and a fragment of the JSON is
// mistaken for a command. A path has no shell metacharacters, so it survives
// every shell layer intact. The file is per-pane so concurrent spawns never
// race on one shared file.
func settingsFile(quilDir, paneID string) string {
	return filepath.Join(quilDir, "sessions", paneID+".settings.json")
}

// WriteSettingsFile writes the hook-settings JSON for paneID to disk and
// returns its absolute path. The daemon passes this path to
// `claude --settings <path>` (claude accepts a file path or an inline JSON
// string). Returns "" with a nil error only when there is nothing to write
// (empty JSON), which lets the caller skip the --settings arg entirely.
func WriteSettingsFile(quilDir, paneID, settingsJSON string) (string, error) {
	if err := validatePaneID(paneID); err != nil {
		return "", err
	}
	if settingsJSON == "" {
		return "", nil
	}
	dir := filepath.Join(quilDir, "sessions")
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return "", fmt.Errorf("create sessions dir: %w", err)
	}
	path := settingsFile(quilDir, paneID)
	if err := atomicWrite(path, []byte(settingsJSON), 0o600); err != nil {
		return "", fmt.Errorf("write hook settings: %w", err)
	}
	return path, nil
}

// sessionIDFile returns the absolute path to <paneID>.id.
func sessionIDFile(quilDir, paneID string) string {
	return filepath.Join(quilDir, "sessions", paneID+".id")
}

// transcriptFile returns the absolute path to <paneID>.transcript, the sidecar
// recording where the pane's session transcript CURRENTLY lives.
//
// It is a separate file so that <paneID>.id keeps exactly one writer. A session
// can migrate mid-flight (an agent moving into a git worktree re-keys the
// project directory), so the path has to be re-recorded after SessionStart —
// but hook invocations are independent processes with no locking, and a
// read-modify-write of the id file would let a Stop that started before a
// concurrent SessionStart write the PRE-rotation id back. That resurrects the
// session the user just left, which is the same wrong-conversation failure this
// whole path exists to prevent. Writing only the sidecar makes that impossible:
// the worst a lost race can do is leave the path stale.
func transcriptFile(quilDir, paneID string) string {
	return filepath.Join(quilDir, "sessions", paneID+".transcript")
}

// SessionRecord is what the hook persists for a pane: the live Claude session
// id, plus the absolute path of that session's transcript.
//
// The path is recorded because it cannot be derived. Claude keys a transcript's
// project directory off the session's OWN working directory, and an agent that
// moves into a git worktree moves the transcript with it — so reconstructing
// the path from the pane's spawn CWD looks in a directory the file was never
// in. TranscriptPath is empty for records written by an older Quil (and for a
// session whose SessionStart carried no path); callers must treat that as
// "unknown", never as "missing".
type SessionRecord struct {
	ID             string
	TranscriptPath string
	ModTime        time.Time
}

// ReadPersistedSession returns the session record the hook last wrote for the
// given pane. A missing file is reported via the returned error satisfying
// errors.Is(err, os.ErrNotExist) so callers can cleanly distinguish "no hook
// fired yet" from a corrupted file.
//
// Reads the file via a single open file descriptor + Stat so the reported
// ModTime always corresponds to the bytes returned, even if the hook rotates
// the file between calls.
func ReadPersistedSession(quilDir, paneID string) (SessionRecord, error) {
	if quilDir == "" {
		return SessionRecord{}, errors.New("claudehook: empty quilDir")
	}
	if err := validatePaneID(paneID); err != nil {
		return SessionRecord{}, err
	}
	f, err := os.Open(sessionIDFile(quilDir, paneID))
	if err != nil {
		return SessionRecord{}, err
	}
	defer f.Close()
	info, err := f.Stat()
	if err != nil {
		return SessionRecord{}, err
	}
	buf, err := io.ReadAll(io.LimitReader(f, maxRecordBytes))
	if err != nil {
		return SessionRecord{ModTime: info.ModTime()}, err
	}
	rec := parseSessionRecord(string(buf))
	rec.ModTime = info.ModTime()
	// The sidecar wins when it describes THIS session: it is written after a
	// mid-session migration, so it is fresher than the path SessionStart
	// recorded. One left behind by a previous session names a different id and
	// is ignored — a path that outlives its id would point at a transcript this
	// session was never in.
	if sid, path := readTranscriptSidecar(quilDir, paneID); path != "" && sid == rec.ID {
		rec.TranscriptPath = path
	}
	return rec, nil
}

// readTranscriptSidecar returns the (session id, transcript path) pair the Stop
// refresh last recorded, or empty strings when there is nothing usable. Every
// failure is silent: the sidecar is an optimisation over the path SessionStart
// already wrote, never a requirement.
func readTranscriptSidecar(quilDir, paneID string) (sessionID, path string) {
	b, err := os.ReadFile(transcriptFile(quilDir, paneID))
	if err != nil || len(b) > maxRecordBytes {
		return "", ""
	}
	rec := parseSessionRecord(string(b))
	return rec.ID, rec.TranscriptPath
}

// maxIDBytes bounds the id line. The record as a whole has to be large enough
// for a long Windows path, but the id within it is a uuid — anything past this
// is a corrupt file, and the value ends up in `claude --resume <id>` argv.
const maxIDBytes = 256

// maxRecordBytes caps a record read: one uuid line plus one path line, sized
// for a long Windows path rather than the bare uuid the file used to hold. The
// cap keeps a malformed or hostile file from forcing us to read megabytes.
const maxRecordBytes = 8 << 10

// parseSessionRecord splits the on-disk record. Line 1 is the session id, line
// 2 (optional) the transcript path. Trimming per line rather than over the
// whole file is what keeps the id clean now that a second line exists — the
// previous whole-file TrimSpace would have returned both glued together.
//
// An over-long id line yields an EMPTY id rather than a truncated one: half a
// corrupt token is not a better resume target than none, and the caller's
// no-session-recorded path is already correct.
func parseSessionRecord(body string) SessionRecord {
	var rec SessionRecord
	lines := strings.SplitN(body, "\n", 3)
	if id := strings.TrimSpace(lines[0]); len(id) <= maxIDBytes {
		rec.ID = id
	}
	if len(lines) > 1 {
		rec.TranscriptPath = strings.TrimSpace(lines[1])
	}
	return rec
}

// ReadPersistedSessionID returns just the session id from the pane's record.
//
// No production caller needs it today — the daemon reads the whole record so it
// can use the transcript path — but it is kept as the package's id-only
// accessor, mirroring opencodehook.ReadPersistedSessionID, and it is the
// narrower contract most of the package's own tests assert against.
func ReadPersistedSessionID(quilDir, paneID string) (id string, modTime time.Time, err error) {
	rec, err := ReadPersistedSession(quilDir, paneID)
	return rec.ID, rec.ModTime, err
}
